before_script:
  - bash .gitlab-ci.sh

variables:
  MYSQL_DATABASE: pemesanan
  MYSQL_ROOT_PASSWORD: secret


phpunit:php7.1:mysql5.6:
  image: php:7.0
  services:
    - mysql:5.6
  script:
    - php vendor/bin/phpunit --colors

phpunit:php7.2:mysql5.6:
  image: php:7.2
  services:
    - mysql:5.6
  script:
    - php vendor/bin/phpunit --colors

phpunit:php7.1:mysql5.7:
  image: php:7.1
  services:
    - mysql:5.7
  script:
    - php vendor/bin/phpunit --colors

phpunit:php7.2:mysql5.7:
  image: php:7.2
  services:
    - mysql:5.7
  script:
    - php vendor/bin/phpunit --colors
